version: "3"
services:

  frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: https://domain.tld
      RAZZLE_PROXY_REWRITE_TARGET: /VirtualHostBase/https/domain.tld:443/Plone/++api++/VirtualHostRoot
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.0
    environment:
      SITE: Plone
    volumes:
      - data:/data
    ports:
    - "8080:8080"

volumes:
  data: {}