version: "3"
services:

  webserver:
    image: nginx
    volumes:
      - ./default.certbot.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]

volumes:
  data: {}